image: python:3.9-alpine

before_script:
  - python -V
  - python -m venv venv
  - source ./venv/bin/activate

stages:
  - test

test:
  before_script:
      - pip install -r requirements-dev.txt
  script:
      - python3 -m pytest --junitxml=test-results.xml tests
  artifacts:
      when: always
      reports:
        junit: test-results.xml
